-- =============================================
-- AOIP — Full Niche & Seed Keyword Reset
-- 30 Niches × 20 Keywords = 600 seed keywords
-- Run in Supabase SQL Editor
-- =============================================

-- STEP 1: Delete all existing niches
-- (CASCADE removes seed_keywords, keywords, competitors,
--  opportunities, community_posts, community_insights, etc.)
DELETE FROM niches;

-- STEP 2: Insert 30 niches
INSERT INTO niches (name, priority, enabled) VALUES
  ('Finance', 10, true),
  ('Students', 9, true),
  ('Productivity', 9, true),
  ('Health', 8, true),
  ('Fitness', 8, true),
  ('Business', 7, true),
  ('Education', 7, true),
  ('AI', 8, true),
  ('Real Estate', 6, true),
  ('Construction', 5, true),
  ('Agriculture', 5, true),
  ('Travel', 6, true),
  ('Parenting', 6, true),
  ('Pets', 5, true),
  ('Freelancers', 7, true),
  ('Creators', 8, true),
  ('Marketing', 7, true),
  ('Sales', 7, true),
  ('Healthcare', 7, true),
  ('Logistics', 5, true),
  ('Retail', 6, true),
  ('Hospitality', 5, true),
  ('Automotive', 5, true),
  ('HR', 6, true),
  ('Recruitment', 6, true),
  ('Legal', 5, true),
  ('Document Tools', 6, true),
  ('Calculators', 6, true),
  ('Trackers', 6, true),
  ('Career Development', 7, true);

-- STEP 3: Insert 600 seed keywords
INSERT INTO seed_keywords (keyword, niche_id)
SELECT v.keyword, n.id
FROM (VALUES
  ('Finance', 'gst calculator'),
  ('Finance', 'sip calculator'),
  ('Finance', 'emi calculator'),
  ('Finance', 'expense tracker'),
  ('Finance', 'budget planner'),
  ('Finance', 'income tax calculator'),
  ('Finance', 'mutual fund tracker'),
  ('Finance', 'stock portfolio tracker'),
  ('Finance', 'personal finance manager'),
  ('Finance', 'money manager app'),
  ('Finance', 'salary calculator india'),
  ('Finance', 'loan calculator'),
  ('Finance', 'fd calculator'),
  ('Finance', 'ppf calculator'),
  ('Finance', 'investment tracker'),
  ('Finance', 'bill reminder app'),
  ('Finance', 'net worth tracker'),
  ('Finance', 'crypto portfolio tracker'),
  ('Finance', 'credit score tracker'),
  ('Finance', 'home loan emi calculator'),
  ('Students', 'attendance tracker app'),
  ('Students', 'exam timetable planner'),
  ('Students', 'study timer app'),
  ('Students', 'assignment tracker'),
  ('Students', 'cgpa calculator'),
  ('Students', 'notes organizer app'),
  ('Students', 'lecture reminder'),
  ('Students', 'exam countdown app'),
  ('Students', 'student planner app'),
  ('Students', 'homework tracker'),
  ('Students', 'college schedule manager'),
  ('Students', 'grade calculator'),
  ('Students', 'pomodoro study timer'),
  ('Students', 'syllabus tracker'),
  ('Students', 'exam preparation app'),
  ('Students', 'student budget tracker'),
  ('Students', 'project deadline tracker'),
  ('Students', 'class routine maker'),
  ('Students', 'study group organizer'),
  ('Students', 'university timetable app'),
  ('Productivity', 'task manager app'),
  ('Productivity', 'to do list app'),
  ('Productivity', 'daily planner app'),
  ('Productivity', 'habit tracker app'),
  ('Productivity', 'goal tracker app'),
  ('Productivity', 'time tracker app'),
  ('Productivity', 'focus timer app'),
  ('Productivity', 'project manager app'),
  ('Productivity', 'note taking app'),
  ('Productivity', 'reminder app'),
  ('Productivity', 'pomodoro timer app'),
  ('Productivity', 'daily routine planner'),
  ('Productivity', 'weekly planner app'),
  ('Productivity', 'kanban board app'),
  ('Productivity', 'work schedule planner'),
  ('Productivity', 'priority task list'),
  ('Productivity', 'digital journal app'),
  ('Productivity', 'meeting notes app'),
  ('Productivity', 'brain dump app'),
  ('Productivity', 'productivity dashboard app'),
  ('Health', 'water intake tracker'),
  ('Health', 'calorie counter app'),
  ('Health', 'bmi calculator app'),
  ('Health', 'period tracker app'),
  ('Health', 'sleep tracker app'),
  ('Health', 'medicine reminder app'),
  ('Health', 'blood pressure tracker'),
  ('Health', 'blood sugar tracker'),
  ('Health', 'symptom checker app'),
  ('Health', 'health diary app'),
  ('Health', 'step counter app'),
  ('Health', 'heart rate tracker'),
  ('Health', 'mental health journal'),
  ('Health', 'pill reminder app'),
  ('Health', 'doctor appointment tracker'),
  ('Health', 'weight loss tracker'),
  ('Health', 'fasting tracker app'),
  ('Health', 'body temperature tracker'),
  ('Health', 'oxygen level tracker'),
  ('Health', 'health report generator'),
  ('Fitness', 'workout tracker app'),
  ('Fitness', 'gym log app'),
  ('Fitness', 'home workout app'),
  ('Fitness', 'exercise planner app'),
  ('Fitness', 'fitness progress tracker'),
  ('Fitness', 'body measurement tracker'),
  ('Fitness', 'push up counter app'),
  ('Fitness', 'running tracker app'),
  ('Fitness', 'yoga timer app'),
  ('Fitness', 'calisthenics workout app'),
  ('Fitness', 'weight training log'),
  ('Fitness', 'rep counter app'),
  ('Fitness', 'fitness challenge app'),
  ('Fitness', 'muscle gain tracker'),
  ('Fitness', 'hiit workout timer'),
  ('Fitness', 'cycling tracker app'),
  ('Fitness', 'personal trainer app'),
  ('Fitness', 'fitness goal planner'),
  ('Fitness', 'workout split planner'),
  ('Fitness', 'no equipment workout app'),
  ('Business', 'invoice generator app'),
  ('Business', 'gst invoice maker'),
  ('Business', 'business expense tracker'),
  ('Business', 'profit loss calculator'),
  ('Business', 'quotation maker app'),
  ('Business', 'client management app'),
  ('Business', 'daily sales tracker'),
  ('Business', 'business card scanner'),
  ('Business', 'cash flow tracker'),
  ('Business', 'small business accounting'),
  ('Business', 'vendor management app'),
  ('Business', 'purchase order app'),
  ('Business', 'inventory management app'),
  ('Business', 'payment receipt maker'),
  ('Business', 'business report generator'),
  ('Business', 'monthly revenue tracker'),
  ('Business', 'order management app'),
  ('Business', 'petty cash tracker'),
  ('Business', 'business plan app'),
  ('Business', 'profit margin calculator'),
  ('Education', 'quiz maker app'),
  ('Education', 'flashcard app'),
  ('Education', 'learning tracker app'),
  ('Education', 'online course organizer'),
  ('Education', 'vocabulary builder app'),
  ('Education', 'math practice app'),
  ('Education', 'language learning app'),
  ('Education', 'typing practice app'),
  ('Education', 'reading tracker app'),
  ('Education', 'knowledge base app'),
  ('Education', 'lesson planner app'),
  ('Education', 'school management app'),
  ('Education', 'parent teacher communication app'),
  ('Education', 'student progress tracker'),
  ('Education', 'education planner app'),
  ('Education', 'certification tracker'),
  ('Education', 'skill learning roadmap'),
  ('Education', 'course notes organizer'),
  ('Education', 'interview preparation app'),
  ('Education', 'competitive exam app'),
  ('AI', 'ai writing assistant app'),
  ('AI', 'ai image generator app'),
  ('AI', 'ai chatbot app'),
  ('AI', 'ai summarizer app'),
  ('AI', 'ai translator app'),
  ('AI', 'ai voice generator'),
  ('AI', 'ai content planner'),
  ('AI', 'ai resume builder'),
  ('AI', 'ai email writer'),
  ('AI', 'ai code helper app'),
  ('AI', 'ai notes app'),
  ('AI', 'ai meeting summarizer'),
  ('AI', 'ai study helper'),
  ('AI', 'ai business plan generator'),
  ('AI', 'ai recipe generator'),
  ('AI', 'ai social media caption generator'),
  ('AI', 'ai presentation maker'),
  ('AI', 'ai pdf summarizer'),
  ('AI', 'ai job description generator'),
  ('AI', 'ai customer support bot'),
  ('Real Estate', 'property price calculator'),
  ('Real Estate', 'home loan eligibility calculator'),
  ('Real Estate', 'rent vs buy calculator'),
  ('Real Estate', 'property tax calculator'),
  ('Real Estate', 'real estate portfolio tracker'),
  ('Real Estate', 'rental income calculator'),
  ('Real Estate', 'construction cost estimator'),
  ('Real Estate', 'flat area calculator'),
  ('Real Estate', 'stamp duty calculator india'),
  ('Real Estate', 'property search organizer'),
  ('Real Estate', 'tenant management app'),
  ('Real Estate', 'lease agreement maker'),
  ('Real Estate', 'property inspection checklist'),
  ('Real Estate', 'real estate deal tracker'),
  ('Real Estate', 'plot size calculator'),
  ('Real Estate', 'home renovation budget planner'),
  ('Real Estate', 'landlord app india'),
  ('Real Estate', 'rental yield calculator'),
  ('Real Estate', 'property valuation app'),
  ('Real Estate', 'real estate crm app'),
  ('Construction', 'construction cost estimator'),
  ('Construction', 'material quantity calculator'),
  ('Construction', 'building area calculator'),
  ('Construction', 'brickwork calculator'),
  ('Construction', 'concrete mix calculator'),
  ('Construction', 'steel quantity calculator'),
  ('Construction', 'project timeline planner'),
  ('Construction', 'labour cost calculator'),
  ('Construction', 'site progress tracker'),
  ('Construction', 'construction daily report'),
  ('Construction', 'plumbing material estimator'),
  ('Construction', 'electrical load calculator'),
  ('Construction', 'paint quantity calculator'),
  ('Construction', 'tile quantity calculator'),
  ('Construction', 'roofing material calculator'),
  ('Construction', 'construction checklist app'),
  ('Construction', 'site attendance tracker'),
  ('Construction', 'drawing measurement app'),
  ('Construction', 'project budget tracker'),
  ('Construction', 'civil work estimator'),
  ('Agriculture', 'crop yield calculator'),
  ('Agriculture', 'fertilizer quantity calculator'),
  ('Agriculture', 'irrigation planner app'),
  ('Agriculture', 'soil health tracker'),
  ('Agriculture', 'farming expense tracker'),
  ('Agriculture', 'weather app for farmers'),
  ('Agriculture', 'crop calendar app'),
  ('Agriculture', 'livestock management app'),
  ('Agriculture', 'seed rate calculator'),
  ('Agriculture', 'pesticide dosage calculator'),
  ('Agriculture', 'farm income tracker'),
  ('Agriculture', 'market price tracker agriculture'),
  ('Agriculture', 'mandi price app india'),
  ('Agriculture', 'crop disease identifier'),
  ('Agriculture', 'farm diary app'),
  ('Agriculture', 'agri loan calculator'),
  ('Agriculture', 'poultry management app'),
  ('Agriculture', 'dairy farm tracker'),
  ('Agriculture', 'harvest planner app'),
  ('Agriculture', 'kisan app india'),
  ('Travel', 'trip planner app'),
  ('Travel', 'travel budget tracker'),
  ('Travel', 'packing list app'),
  ('Travel', 'itinerary maker app'),
  ('Travel', 'travel expense tracker'),
  ('Travel', 'flight price tracker'),
  ('Travel', 'hotel booking organizer'),
  ('Travel', 'visa checklist app'),
  ('Travel', 'road trip planner'),
  ('Travel', 'travel journal app'),
  ('Travel', 'currency converter offline'),
  ('Travel', 'distance calculator app'),
  ('Travel', 'travel document organizer'),
  ('Travel', 'group trip expense splitter'),
  ('Travel', 'train journey planner india'),
  ('Travel', 'cab expense tracker'),
  ('Travel', 'travel insurance calculator'),
  ('Travel', 'solo travel planner'),
  ('Travel', 'bucket list travel app'),
  ('Travel', 'holiday planner app'),
  ('Parenting', 'baby growth tracker'),
  ('Parenting', 'child vaccination tracker'),
  ('Parenting', 'pregnancy tracker app'),
  ('Parenting', 'baby feeding tracker'),
  ('Parenting', 'child development milestones'),
  ('Parenting', 'parenting journal app'),
  ('Parenting', 'baby sleep tracker'),
  ('Parenting', 'school fee tracker'),
  ('Parenting', 'kids activity planner'),
  ('Parenting', 'chore chart app for kids'),
  ('Parenting', 'baby weight calculator'),
  ('Parenting', 'child medicine reminder'),
  ('Parenting', 'kids screen time tracker'),
  ('Parenting', 'potty training tracker'),
  ('Parenting', 'child height calculator'),
  ('Parenting', 'baby name finder app'),
  ('Parenting', 'pregnancy week calculator'),
  ('Parenting', 'family expense tracker'),
  ('Parenting', 'kids homework planner'),
  ('Parenting', 'child immunization schedule'),
  ('Pets', 'pet health tracker'),
  ('Pets', 'dog vaccination tracker'),
  ('Pets', 'pet medicine reminder'),
  ('Pets', 'pet weight tracker'),
  ('Pets', 'dog food calculator'),
  ('Pets', 'cat care tracker'),
  ('Pets', 'pet expense tracker'),
  ('Pets', 'pet diary app'),
  ('Pets', 'dog training log'),
  ('Pets', 'aquarium water calculator'),
  ('Pets', 'pet age calculator'),
  ('Pets', 'vet appointment reminder'),
  ('Pets', 'dog walk tracker'),
  ('Pets', 'pet birthday reminder'),
  ('Pets', 'fish tank maintenance app'),
  ('Pets', 'bird care tracker'),
  ('Pets', 'pet grooming reminder'),
  ('Pets', 'pet insurance tracker'),
  ('Pets', 'dog breed identifier'),
  ('Pets', 'animal feeding schedule app'),
  ('Freelancers', 'freelance invoice generator'),
  ('Freelancers', 'project time tracker'),
  ('Freelancers', 'client management app'),
  ('Freelancers', 'freelance income tracker'),
  ('Freelancers', 'contract generator app'),
  ('Freelancers', 'hourly rate calculator'),
  ('Freelancers', 'project proposal maker'),
  ('Freelancers', 'freelance expense tracker'),
  ('Freelancers', 'work log app'),
  ('Freelancers', 'payment tracker for freelancers'),
  ('Freelancers', 'client onboarding checklist'),
  ('Freelancers', 'project deadline tracker'),
  ('Freelancers', 'freelance tax calculator india'),
  ('Freelancers', 'milestone tracker app'),
  ('Freelancers', 'quote generator app'),
  ('Freelancers', 'retainer invoice app'),
  ('Freelancers', 'billable hours tracker'),
  ('Freelancers', 'freelance portfolio organizer'),
  ('Freelancers', 'project profitability calculator'),
  ('Freelancers', 'freelancer crm app'),
  ('Creators', 'content calendar app'),
  ('Creators', 'youtube analytics tracker'),
  ('Creators', 'instagram post planner'),
  ('Creators', 'social media scheduler'),
  ('Creators', 'content idea generator'),
  ('Creators', 'video script planner'),
  ('Creators', 'subscriber growth tracker'),
  ('Creators', 'creator income tracker'),
  ('Creators', 'brand deal tracker'),
  ('Creators', 'thumbnail maker app'),
  ('Creators', 'hashtag generator app'),
  ('Creators', 'reel planner app'),
  ('Creators', 'podcast planner app'),
  ('Creators', 'creator expense tracker'),
  ('Creators', 'audience analytics app'),
  ('Creators', 'sponsorship tracker'),
  ('Creators', 'content repurposing planner'),
  ('Creators', 'newsletter planner app'),
  ('Creators', 'community manager app'),
  ('Creators', 'creator collaboration tracker'),
  ('Marketing', 'marketing campaign tracker'),
  ('Marketing', 'social media analytics app'),
  ('Marketing', 'email campaign tracker'),
  ('Marketing', 'lead generation tracker'),
  ('Marketing', 'marketing budget planner'),
  ('Marketing', 'seo keyword tracker'),
  ('Marketing', 'roi calculator marketing'),
  ('Marketing', 'ad spend tracker'),
  ('Marketing', 'marketing calendar app'),
  ('Marketing', 'competitor analysis app'),
  ('Marketing', 'brand monitoring app'),
  ('Marketing', 'utm link builder'),
  ('Marketing', 'conversion rate calculator'),
  ('Marketing', 'content performance tracker'),
  ('Marketing', 'marketing report generator'),
  ('Marketing', 'customer journey mapper'),
  ('Marketing', 'ab test tracker'),
  ('Marketing', 'influencer campaign tracker'),
  ('Marketing', 'marketing kpi dashboard'),
  ('Marketing', 'google ads calculator'),
  ('Sales', 'sales target tracker'),
  ('Sales', 'daily sales report app'),
  ('Sales', 'crm app for sales'),
  ('Sales', 'lead pipeline tracker'),
  ('Sales', 'sales commission calculator'),
  ('Sales', 'cold call tracker'),
  ('Sales', 'follow up reminder app'),
  ('Sales', 'sales forecast calculator'),
  ('Sales', 'quotation maker'),
  ('Sales', 'deal closure tracker'),
  ('Sales', 'customer visit log'),
  ('Sales', 'sales performance dashboard'),
  ('Sales', 'prospect list manager'),
  ('Sales', 'sales script organizer'),
  ('Sales', 'revenue goal tracker'),
  ('Sales', 'b2b sales tracker'),
  ('Sales', 'door to door sales app'),
  ('Sales', 'field sales app india'),
  ('Sales', 'demo tracker app'),
  ('Sales', 'sales conversion calculator'),
  ('Healthcare', 'patient appointment manager'),
  ('Healthcare', 'doctor schedule planner'),
  ('Healthcare', 'opd billing app'),
  ('Healthcare', 'prescription writer app'),
  ('Healthcare', 'clinic management app'),
  ('Healthcare', 'hospital expense tracker'),
  ('Healthcare', 'medical record organizer'),
  ('Healthcare', 'patient follow up reminder'),
  ('Healthcare', 'health camp planner'),
  ('Healthcare', 'nurse duty scheduler'),
  ('Healthcare', 'diagnostic report organizer'),
  ('Healthcare', 'pharmacy stock tracker'),
  ('Healthcare', 'insurance claim tracker'),
  ('Healthcare', 'telemedicine log app'),
  ('Healthcare', 'patient history app'),
  ('Healthcare', 'lab report manager'),
  ('Healthcare', 'dental appointment tracker'),
  ('Healthcare', 'physiotherapy session tracker'),
  ('Healthcare', 'doctor visit log'),
  ('Healthcare', 'medical billing app india'),
  ('Logistics', 'delivery tracking app'),
  ('Logistics', 'vehicle expense tracker'),
  ('Logistics', 'fuel consumption calculator'),
  ('Logistics', 'freight cost calculator'),
  ('Logistics', 'driver attendance tracker'),
  ('Logistics', 'route planner app'),
  ('Logistics', 'vehicle maintenance tracker'),
  ('Logistics', 'fleet management app'),
  ('Logistics', 'cargo weight calculator'),
  ('Logistics', 'shipment log app'),
  ('Logistics', 'warehouse checklist app'),
  ('Logistics', 'delivery receipt generator'),
  ('Logistics', 'logistics expense tracker'),
  ('Logistics', 'km tracker for drivers'),
  ('Logistics', 'toll calculator india'),
  ('Logistics', 'truck load calculator'),
  ('Logistics', 'inventory dispatch tracker'),
  ('Logistics', 'supply chain tracker'),
  ('Logistics', 'order fulfillment tracker'),
  ('Logistics', 'vehicle service reminder'),
  ('Retail', 'shop inventory manager'),
  ('Retail', 'daily sales tracker'),
  ('Retail', 'billing app for shop'),
  ('Retail', 'barcode scanner app'),
  ('Retail', 'stock alert app'),
  ('Retail', 'retail expense tracker'),
  ('Retail', 'shop profit calculator'),
  ('Retail', 'purchase order tracker'),
  ('Retail', 'vendor payment tracker'),
  ('Retail', 'customer loyalty tracker'),
  ('Retail', 'product catalogue app'),
  ('Retail', 'shop ledger app'),
  ('Retail', 'monthly sales report'),
  ('Retail', 'shopkeeper accounting app'),
  ('Retail', 'discount calculator app'),
  ('Retail', 'gst billing app'),
  ('Retail', 'retail crm app'),
  ('Retail', 'reorder level tracker'),
  ('Retail', 'shop attendance app'),
  ('Retail', 'pos app for small shops'),
  ('Hospitality', 'hotel room booking tracker'),
  ('Hospitality', 'restaurant order manager'),
  ('Hospitality', 'table reservation app'),
  ('Hospitality', 'food cost calculator'),
  ('Hospitality', 'staff scheduling app'),
  ('Hospitality', 'guest feedback tracker'),
  ('Hospitality', 'hotel billing app'),
  ('Hospitality', 'menu maker app'),
  ('Hospitality', 'kitchen order tracker'),
  ('Hospitality', 'housekeeping checklist app'),
  ('Hospitality', 'occupancy rate calculator'),
  ('Hospitality', 'restaurant inventory app'),
  ('Hospitality', 'catering cost calculator'),
  ('Hospitality', 'hotel expense tracker'),
  ('Hospitality', 'banquet booking manager'),
  ('Hospitality', 'shift planner for staff'),
  ('Hospitality', 'hotel check in app'),
  ('Hospitality', 'guest review tracker'),
  ('Hospitality', 'food waste tracker'),
  ('Hospitality', 'restaurant profit calculator'),
  ('Automotive', 'vehicle service tracker'),
  ('Automotive', 'car maintenance reminder'),
  ('Automotive', 'fuel mileage calculator'),
  ('Automotive', 'tyre pressure tracker'),
  ('Automotive', 'car expense tracker'),
  ('Automotive', 'vehicle insurance reminder'),
  ('Automotive', 'rc renewal reminder'),
  ('Automotive', 'car loan emi calculator'),
  ('Automotive', 'auto repair estimate app'),
  ('Automotive', 'driver log app'),
  ('Automotive', 'vehicle inspection checklist'),
  ('Automotive', 'car resale value calculator'),
  ('Automotive', 'engine oil change tracker'),
  ('Automotive', 'auto parts inventory'),
  ('Automotive', 'roadside assistance log'),
  ('Automotive', 'car wash expense tracker'),
  ('Automotive', 'driving log app'),
  ('Automotive', 'vehicle fleet tracker'),
  ('Automotive', 'bike service reminder'),
  ('Automotive', 'ev charging tracker'),
  ('HR', 'employee attendance tracker'),
  ('HR', 'leave management app'),
  ('HR', 'payroll calculator app'),
  ('HR', 'hr document organizer'),
  ('HR', 'employee onboarding checklist'),
  ('HR', 'salary slip generator'),
  ('HR', 'performance review tracker'),
  ('HR', 'overtime calculator'),
  ('HR', 'workforce planner app'),
  ('HR', 'employee birthday reminder'),
  ('HR', 'shift roster app'),
  ('HR', 'exit interview tracker'),
  ('HR', 'hr policy organizer'),
  ('HR', 'recruitment pipeline tracker'),
  ('HR', 'training attendance tracker'),
  ('HR', 'employee kpi tracker'),
  ('HR', 'pf esi calculator india'),
  ('HR', 'team productivity tracker'),
  ('HR', 'headcount planner'),
  ('HR', 'hr compliance checklist'),
  ('Recruitment', 'job application tracker'),
  ('Recruitment', 'candidate pipeline manager'),
  ('Recruitment', 'interview scheduler app'),
  ('Recruitment', 'resume organizer app'),
  ('Recruitment', 'hiring checklist app'),
  ('Recruitment', 'job offer tracker'),
  ('Recruitment', 'recruitment crm app'),
  ('Recruitment', 'interview feedback form'),
  ('Recruitment', 'candidate evaluation app'),
  ('Recruitment', 'job description maker'),
  ('Recruitment', 'onboarding tracker'),
  ('Recruitment', 'background check tracker'),
  ('Recruitment', 'hiring funnel tracker'),
  ('Recruitment', 'recruitment cost calculator'),
  ('Recruitment', 'talent pool manager'),
  ('Recruitment', 'interview question bank'),
  ('Recruitment', 'shortlisting tracker'),
  ('Recruitment', 'placement tracker app'),
  ('Recruitment', 'internship tracker'),
  ('Recruitment', 'campus recruitment planner'),
  ('Legal', 'contract maker app'),
  ('Legal', 'legal document organizer'),
  ('Legal', 'court date reminder'),
  ('Legal', 'legal expense tracker'),
  ('Legal', 'case management app'),
  ('Legal', 'client legal tracker'),
  ('Legal', 'nda generator app'),
  ('Legal', 'legal deadline reminder'),
  ('Legal', 'compliance checklist app'),
  ('Legal', 'law firm billing app'),
  ('Legal', 'legal research notes app'),
  ('Legal', 'litigation tracker'),
  ('Legal', 'document signing tracker'),
  ('Legal', 'legal fee calculator'),
  ('Legal', 'client onboarding legal app'),
  ('Legal', 'agreement maker app'),
  ('Legal', 'court hearing planner'),
  ('Legal', 'ip trademark tracker'),
  ('Legal', 'legal task manager'),
  ('Legal', 'lawyer time tracker'),
  ('Document Tools', 'pdf converter app'),
  ('Document Tools', 'document scanner app'),
  ('Document Tools', 'pdf editor app'),
  ('Document Tools', 'digital signature app'),
  ('Document Tools', 'document organizer app'),
  ('Document Tools', 'pdf merger app'),
  ('Document Tools', 'word to pdf converter'),
  ('Document Tools', 'invoice pdf maker'),
  ('Document Tools', 'document template maker'),
  ('Document Tools', 'file compress app'),
  ('Document Tools', 'pdf annotator app'),
  ('Document Tools', 'business letter maker'),
  ('Document Tools', 'certificate maker app'),
  ('Document Tools', 'form builder app'),
  ('Document Tools', 'receipt scanner app'),
  ('Document Tools', 'document watermark app'),
  ('Document Tools', 'pdf password protector'),
  ('Document Tools', 'document version tracker'),
  ('Document Tools', 'file renamer app'),
  ('Document Tools', 'letterhead maker app'),
  ('Calculators', 'scientific calculator app'),
  ('Calculators', 'percentage calculator app'),
  ('Calculators', 'age calculator app'),
  ('Calculators', 'unit converter app'),
  ('Calculators', 'date difference calculator'),
  ('Calculators', 'tip calculator app'),
  ('Calculators', 'discount calculator app'),
  ('Calculators', 'currency converter app'),
  ('Calculators', 'square footage calculator'),
  ('Calculators', 'compound interest calculator'),
  ('Calculators', 'fraction calculator app'),
  ('Calculators', 'number system converter'),
  ('Calculators', 'ratio calculator app'),
  ('Calculators', 'area volume calculator'),
  ('Calculators', 'calories burned calculator'),
  ('Calculators', 'loan interest calculator'),
  ('Calculators', 'speed distance time calculator'),
  ('Calculators', 'income tax calculator india'),
  ('Calculators', 'concrete quantity calculator'),
  ('Calculators', 'fuel cost calculator'),
  ('Trackers', 'habit tracker app'),
  ('Trackers', 'expense tracker app'),
  ('Trackers', 'weight tracker app'),
  ('Trackers', 'goal tracker app'),
  ('Trackers', 'mood tracker app'),
  ('Trackers', 'reading tracker app'),
  ('Trackers', 'net worth tracker app'),
  ('Trackers', 'subscription tracker app'),
  ('Trackers', 'water intake tracker'),
  ('Trackers', 'medicine tracker app'),
  ('Trackers', 'workout progress tracker'),
  ('Trackers', 'daily journal tracker'),
  ('Trackers', 'project progress tracker'),
  ('Trackers', 'sleep quality tracker'),
  ('Trackers', 'screen time tracker'),
  ('Trackers', 'income expense tracker'),
  ('Trackers', 'debt payoff tracker'),
  ('Trackers', 'savings goal tracker'),
  ('Trackers', 'productivity tracker app'),
  ('Trackers', 'food diary tracker app'),
  ('Career Development', 'resume builder app'),
  ('Career Development', 'job search tracker'),
  ('Career Development', 'interview preparation app'),
  ('Career Development', 'skill development tracker'),
  ('Career Development', 'linkedin profile optimizer'),
  ('Career Development', 'career goal planner'),
  ('Career Development', 'networking contact tracker'),
  ('Career Development', 'salary negotiation guide'),
  ('Career Development', 'certification tracker app'),
  ('Career Development', 'portfolio builder app'),
  ('Career Development', 'mentor tracker app'),
  ('Career Development', 'job offer comparison tool'),
  ('Career Development', 'cover letter maker'),
  ('Career Development', 'professional development planner'),
  ('Career Development', 'job application organizer'),
  ('Career Development', 'career roadmap planner'),
  ('Career Development', 'upskilling tracker'),
  ('Career Development', 'career journal app'),
  ('Career Development', 'performance review prep app'),
  ('Career Development', 'promotion goal tracker')
) AS v(niche_name, keyword)
JOIN niches n ON n.name = v.niche_name
ON CONFLICT (keyword, niche_id) DO NOTHING;

-- Verify counts
SELECT n.name, COUNT(sk.id) AS seed_keyword_count
FROM niches n
LEFT JOIN seed_keywords sk ON sk.niche_id = n.id
GROUP BY n.name
ORDER BY n.name;